title: Pinepods Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://example.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Pinepods Docs
      category: Pinepods
      description: "This is the Documentation Site. "
    - name: Pinepods Trial Site
      category: Pinepods
      description: This is the Trial Pinepods Site for testing the app
    - name: Pinepods Search API
      description: This is the search API for Podcast Index and Itunes searching
      category: Pinepods
      link: https://example.com/
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/pinepods-logo.jpeg
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Pinepods Trial Site
      link: https://try.pinepods.online
    - name: Pinepods Doc Site
      link: https://pinepods.online
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Pinepods
      description: ""
      closed: true
  description: This site will monitor the status of Pinepods and it's supporting
    sites, if there's an issue a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
